name: TecnoPOS
version: '${project.version}'
main: me.wiceh.tecnopos.TecnoPOS
author: wIceh
softdepend: [ Vault ]
description: Plugin simile al POS di TecnoCraft
commands:
  pos:
    description: "Ottieni il POS"
    aliases: [ tecnopos, tpos ]